In [1]:
import numpy as np

a = np.array(range(10))
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
print(np.where(a<5))

(array([0, 1, 2, 3, 4], dtype=int64),)


In [3]:
a = np.array([range(5), range(5,10)])
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
print(np.where(a%2==0))

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 2, 4, 1, 3], dtype=int64))


In [2]:
print( 3%2)

1


In [15]:
cost = np.array([[1,2,3,4],
               [4,5,6,7],
               [8,9,10,11]], dtype=float)
print(cost)

left_cost = np.roll(cost, shift=(1,1), axis=(0,1))
right_cost = np.roll(cost, shift=(1,-1), axis=(0,1))

left_cost[0] = np.inf
right_cost[0] = np.inf

left_cost[:, [0,-1]] = np.inf
# left_cost[:, -1] = np.inf
right_cost[:, [0,-1]] = np.inf
# right_cost[:, -1] = np.inf

print(left_cost)
print(right_cost)

[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[inf inf inf inf]
 [inf  1.  2. inf]
 [inf  4.  5. inf]]
[[inf inf inf inf]
 [inf  3.  4. inf]
 [inf  6.  7. inf]]


In [8]:
import numpy as np
from scipy.spatial.distance import pdist, squareform
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12], dtype=float).reshape(6,2)
print(a)
pd = pdist(a, metric='euclidean')
print(pd.shape) # size of pd is n(n-1)/2
print(pd) 
sqfd = squareform(pd)
print(sqfd.shape)
print(sqfd)

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11. 12.]]
(15,)
[ 2.82842712  5.65685425  8.48528137 11.3137085  14.14213562  2.82842712
  5.65685425  8.48528137 11.3137085   2.82842712  5.65685425  8.48528137
  2.82842712  5.65685425  2.82842712]
(6, 6)
[[ 0.          2.82842712  5.65685425  8.48528137 11.3137085  14.14213562]
 [ 2.82842712  0.          2.82842712  5.65685425  8.48528137 11.3137085 ]
 [ 5.65685425  2.82842712  0.          2.82842712  5.65685425  8.48528137]
 [ 8.48528137  5.65685425  2.82842712  0.          2.82842712  5.65685425]
 [11.3137085   8.48528137  5.65685425  2.82842712  0.          2.82842712]
 [14.14213562 11.3137085   8.48528137  5.65685425  2.82842712  0.        ]]


In [11]:
mgrid = np.mgrid[0:4, 0:3]
print(mgrid)

[[[0 0 0]
  [1 1 1]
  [2 2 2]
  [3 3 3]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]]
