In [1]:
import numpy as np

a = np.array(range(10))
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
print(np.where(a<5))

(array([0, 1, 2, 3, 4], dtype=int64),)


In [3]:
a = np.array([range(5), range(5,10)])
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
print(np.where(a%2==0))

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 2, 4, 1, 3], dtype=int64))


In [15]:
cost = np.array([[1,2,3,4],
               [4,5,6,7],
               [8,9,10,11]], dtype=float)
print(cost)

left_cost = np.roll(cost, shift=(1,1), axis=(0,1))
right_cost = np.roll(cost, shift=(1,-1), axis=(0,1))

left_cost[0] = np.inf
right_cost[0] = np.inf

left_cost[:, [0,-1]] = np.inf
# left_cost[:, -1] = np.inf
right_cost[:, [0,-1]] = np.inf
# right_cost[:, -1] = np.inf

print(left_cost)
print(right_cost)

[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[inf inf inf inf]
 [inf  1.  2. inf]
 [inf  4.  5. inf]]
[[inf inf inf inf]
 [inf  3.  4. inf]
 [inf  6.  7. inf]]
