In [3]:
import numpy as np

a = np.array(range(10))
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(np.where(a<5))

(array([0, 1, 2, 3, 4], dtype=int64),)


In [5]:
a = np.array([range(5), range(5,10)])
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
print(np.where(a%2==0))

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 2, 4, 1, 3], dtype=int64))
